signal:
    nclass: 1
    nlayer: 1
    num_heads: 1
    hidden_dim: 16
    epoch: 2000
    lr: 0.01
    weight_decay: 0.0
    tran_dropout: 0.0
    feat_dropout: 0.0
    prop_dropout: 0.0
    norm: 'layer'
cora:
    nclass: 7
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
citeseer:
    nclass: 6
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
# photo:
#     nclass: 8
#     nlayer: 2
#     num_heads: 4
#     hidden_dim: 32
#     epoch: 2000
#     lr: 0.0002
#     weight_decay: 0.0001
#     tran_dropout: 0.2
#     feat_dropout: 0.3
#     prop_dropout: 0.2
#     norm: 'layer'
arxiv:
    nclass: 40
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
arxivyear:
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
bookchild:
    nclass: 24
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
bookhis:
    nclass: 12
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
cornell:
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
texas:
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
wisconsin:
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
washington:
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
sportsfit:
    nclass: 13
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
wikics:
    nclass: 10
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
amazon_ratings:
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
pubmed:
    nclass: 3
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
photo: # 重做
    nclass: 12
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
computers:
    nclass: 10
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
chameleon:
    nclass: 5
    nlayer: 2
    num_heads: 4
    hidden_dim: 32
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0005
    tran_dropout: 0.2
    feat_dropout: 0.4
    prop_dropout: 0.5
    norm: 'layer'
squirrel:
    nclass: 5
    nlayer: 2
    num_heads: 2
    hidden_dim: 32
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.1
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'layer'
actor:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'layer'
penn:
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.0
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'layer'
